"""Generate Spaces artwork from resources/brand-source.jpg (requires Pillow).

Run after replacing the source. Embedded assets keep desktop and DSH plugin
bundles independent of the launch directory and external asset servers.
"""
import base64
from io import BytesIO
from pathlib import Path

from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
resources = root / "resources"
source = ImageOps.exif_transpose(Image.open(resources / "brand-source.jpg")).convert("RGB")
if source.width != source.height:
    raise ValueError("Brand artwork must be square")

icons = {}
for name, size in [("icon", 256), ("mac-icon", 1024), ("tray-icon", 32)]:
    output = resources / f"{name}.png"
    source.resize((size, size), Image.Resampling.LANCZOS).save(output, optimize=True)
    icons[name] = base64.b64encode(output.read_bytes()).decode("ascii")

web = BytesIO()
source.resize((512, 512), Image.Resampling.LANCZOS).save(web, "JPEG", quality=90, optimize=True)
header = "// Generated by scripts/render-brand-icons.py. Do not edit by hand.\n"
(root / "src/shared/brand-artwork.ts").write_text(
    header + 'export const BRAND_IMAGE_URL = "data:image/jpeg;base64,'
    + base64.b64encode(web.getvalue()).decode("ascii") + '";\n', encoding="utf-8")
(root / "src/main/brand-icons.ts").write_text(
    header + f'export const APP_PNG_BASE64 = "{icons["icon"]}";\n'
    + f'export const TRAY_PNG_BASE64 = "{icons["tray-icon"]}";\n', encoding="utf-8")
print("Generated app, macOS, tray and web artwork")
